# Generated by Django 5.0.6 on 2024-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_id_producto_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventana',
            field=models.CharField(default='principal', max_length=50),
        ),
    ]
