# Generated by Django 5.0.6 on 2024-07-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_producto_ventana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ventana',
            field=models.CharField(default='ventana_gato', max_length=50),
        ),
    ]
